# Generated by Django 2.2 on 2020-07-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentBLG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='qq',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
