# Generated by Django 2.2 on 2020-07-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentBLG', '0003_auto_20200708_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_certified',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='today_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='today_lookup',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='today_release',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ps_motto',
            field=models.TextField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='qq',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='vip_level',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
